const SUPABASE_URL='https://buajzipyrrbkbvryaopx.supabase.co';
const SUPABASE_KEY='sb_publishable_hCbIMTVIb_LFY0T8Cxtx-Q_YblhFoyF';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const colors=['#56C2FF','#FF9F43','#7CE38B','#F5F5F5','#FF6868','#FFD166','#B98CFF','#59E3D5','#F38BD9','#A2C55F'];
const $=id=>document.getElementById(id);
const E={home:$('homeScreen'),setup:$('setupScreen'),game:$('gameScreen'),inputs:$('teamInputs'),add:$('addTeamBtn'),start:$('startSessionBtn'),duration:$('durationSelect'),players:$('playersSelect'),host:$('hostGameBtn'),join:$('joinBtn'),joinCode:$('joinCode'),joinError:$('joinError'),aGoal:$('teamAGoal'),bGoal:$('teamBGoal'),aName:$('teamAName'),bName:$('teamBName'),aColor:$('teamAColor'),bColor:$('teamBColor'),timer:$('timer'),pause:$('pauseBtn'),draw:$('drawBtn'),nextName:$('nextTeamName'),nextColor:$('nextColor'),nextEta:$('nextEta'),queue:$('queueList'),queueCount:$('queueCount'),undo:$('undoBtn'),history:$('historyBtn'),reset:$('resetBtn'),modal:$('confirmModal'),confirmTitle:$('confirmTitle'),confirmText:$('confirmText'),cancel:$('cancelConfirm'),confirm:$('confirmAction'),sheet:$('historySheet'),closeHistory:$('closeHistory'),historyList:$('historyList'),toast:$('toast'),room:$('roomBadge'),role:$('roleLabel'),share:$('shareModal'),shareCode:$('shareRoomCode'),qr:$('qrCode'),copyLink:$('copyRoomLink'),closeShare:$('closeShare'),transition:$('transitionOverlay'),transitionKicker:$('transitionKicker'),transitionTitle:$('transitionTitle'),transitionText:$('transitionText'),matches:$('matchesPlayed'),leader:$('leaderName'),leaderWins:$('leaderWins')};
let role='none',roomCode=null,hostToken=null,channel=null,tick=null,pending=null,actionLock=false,fullTimeLock=false,minuteAlertKey='';
let state={teams:[],queue:[],playing:[],history:[],snapshots:[],duration:600,remaining:600,running:false,endsAt:null,matchId:null};
function screen(x){[E.home,E.setup,E.game].forEach(e=>e.classList.remove('active'));x.classList.add('active')}
function toast(m){E.toast.textContent=m;E.toast.classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>E.toast.classList.add('hidden'),2200)}
function addTeam(name=''){if(E.inputs.children.length>=10)return toast('Maximum 10 teams');let i=E.inputs.children.length,r=document.createElement('div');r.className='team-input-row';r.innerHTML=`<span class="color-chip" style="background:${colors[i%10]}"></span><input class="team-input" value="${name||`Team ${i+1}`}"><button class="remove-team">×</button>`;r.querySelector('button').onclick=()=>{if(E.inputs.children.length>4)r.remove();else toast('You need at least 4 teams')};E.inputs.appendChild(r)}
for(let i=0;i<5;i++)addTeam();E.add.onclick=()=>addTeam();E.host.onclick=()=>screen(E.setup);
function publicState(){let x={...state};delete x.snapshots;return x}
async function push(){if(role!=='host')return;let {error}=await sb.rpc('update_session_state',{p_code:roomCode,p_host_token:hostToken,p_state:publicState(),p_status:'active'});if(error)toast('Sync problem — your phone is still keeping the game')}
function freshMatch(){state.matchId=crypto.randomUUID();state.remaining=state.duration;state.running=true;state.endsAt=new Date(Date.now()+state.duration*1000).toISOString();fullTimeLock=false;minuteAlertKey=''}
async function createRoom(){let names=[...document.querySelectorAll('.team-input')].map(x=>x.value.trim()).filter(Boolean);if(names.length<4)return toast('Add at least 4 teams');if(new Set(names.map(x=>x.toLowerCase())).size!==names.length)return toast('Team names must be unique');state.teams=names.map((name,i)=>({id:crypto.randomUUID(),name,color:colors[i%10],games:0,wins:0,draws:0,streak:0}));state.playing=state.teams.slice(0,2);state.queue=state.teams.slice(2);state.duration=+E.duration.value;state.history=[];state.snapshots=[];freshMatch();let {data,error}=await sb.rpc('create_session',{p_name:'Sunday Football',p_duration_seconds:state.duration,p_players_per_team:+E.players.value,p_state:publicState()});if(error)return toast('Could not create room');let r=Array.isArray(data)?data[0]:data;roomCode=r.code;hostToken=r.host_token;role='host';localStorage.setItem('playnext-host',JSON.stringify({roomCode,hostToken}));enterGame();await subscribe()}
E.start.onclick=createRoom;
async function getRoom(code){let {data,error}=await sb.rpc('join_session',{p_code:code});let r=Array.isArray(data)?data[0]:data;return error?null:r}
async function joinRoom(){let code=E.joinCode.value.replace(/\D/g,'').slice(0,4);E.joinError.textContent='';if(code.length!==4){E.joinError.textContent='Enter the 4-digit room code';return}let r=await getRoom(code);if(!r){E.joinError.textContent='Room not found';return}roomCode=code;role='spectator';state={...state,...r.state};enterGame();await subscribe()}
E.join.onclick=joinRoom;E.joinCode.oninput=()=>E.joinCode.value=E.joinCode.value.replace(/\D/g,'').slice(0,4);E.joinCode.onkeydown=e=>{if(e.key==='Enter')joinRoom()};
async function recoverHost(){try{let saved=JSON.parse(localStorage.getItem('playnext-host')||'null');if(!saved?.roomCode||!saved?.hostToken)return;let r=await getRoom(saved.roomCode);if(!r||r.status==='ended'){localStorage.removeItem('playnext-host');return}roomCode=saved.roomCode;hostToken=saved.hostToken;role='host';state={...state,...r.state};enterGame();await subscribe();toast('Hosted session restored')}catch(e){localStorage.removeItem('playnext-host')}}
function enterGame(){screen(E.game);document.body.classList.toggle('spectator',role==='spectator');E.role.textContent=role==='host'?'HOST · LIVE SESSION':'SPECTATOR · LIVE';E.room.innerHTML=`ROOM <span class="share-code">${roomCode}</span> ↗`;render();startTicker()}
async function subscribe(){if(channel)await sb.removeChannel(channel);channel=sb.channel('room-'+roomCode).on('postgres_changes',{event:'UPDATE',schema:'public',table:'sessions',filter:`code=eq.${roomCode}`},p=>{if(role==='spectator'){state={...state,...p.new.state};render()}}).subscribe()}
function currentRemaining(){if(state.running&&state.endsAt)return Math.max(0,Math.ceil((new Date(state.endsAt).getTime()-Date.now())/1000));return state.remaining??state.duration}
function alertUser(kind){if(navigator.vibrate)navigator.vibrate(kind==='full'?[200,120,300]:120);try{let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let c=new A(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=kind==='full'?720:520;g.gain.value=.035;o.start();o.stop(c.currentTime+.13)}catch(e){}}
function startTicker(){clearInterval(tick);tick=setInterval(()=>{let r=currentRemaining();renderTimer(r);let key=state.matchId||state.endsAt;if(state.running&&r<=60&&r>0&&minuteAlertKey!==key){minuteAlertKey=key;alertUser('minute');if(role==='host')toast('1 minute remaining')}if(role==='host'&&state.running&&r<=0&&!fullTimeLock){fullTimeLock=true;state.remaining=0;state.running=false;state.endsAt=null;alertUser('full');render();openConfirm('draw',null,true)}},250)}
function startClock(sync=true){state.remaining=state.remaining??state.duration;state.running=true;state.endsAt=new Date(Date.now()+state.remaining*1000).toISOString();fullTimeLock=false;E.pause.textContent='Pause';if(sync)push()}
function pauseClock(sync=true){state.remaining=currentRemaining();state.running=false;state.endsAt=null;E.pause.textContent='Resume';if(sync)push()}
E.pause.onclick=()=>state.running?pauseClock():startClock();
function renderTimer(r=currentRemaining()){let m=Math.floor(r/60),s=r%60;E.timer.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;E.timer.classList.toggle('timer-warning',r<=60)}
function render(){if(state.playing.length<2)return;let[a,b]=state.playing;E.aName.textContent=a.name;E.bName.textContent=b.name;E.aColor.style.background=a.color;E.bColor.style.background=b.color;renderTimer();let n=state.queue[0],mins=Math.max(1,Math.round(state.duration/60));E.nextName.textContent=n?.name||'—';if(n)E.nextColor.style.background=n.color;E.nextEta.textContent=n?'GET READY':'';E.queueCount.textContent=`${state.queue.length} waiting`;E.queue.innerHTML=state.queue.map((t,i)=>`<div class="queue-item ${i===0?'queue-next':''}"><span class="queue-pos">${i+1}</span><span class="team-dot" style="background:${t.color}"></span><span class="queue-name">${t.name}</span><span class="queue-wait">${i===0?'Next':`up to ~${(i+1)*mins} min`}</span></div>`).join('');E.pause.textContent=state.running?'Pause':'Resume';let played=state.history.length,leader=[...state.teams].sort((x,y)=>(y.wins||0)-(x.wins||0))[0];if(E.matches)E.matches.textContent=played;if(E.leader)E.leader.textContent=leader?.name||'—';if(E.leaderWins)E.leaderWins.textContent=leader?.wins||0}
function snap(){state.snapshots.push(JSON.stringify({teams:state.teams,queue:state.queue,playing:state.playing,history:state.history}));if(state.snapshots.length>20)state.snapshots.shift()}
function openConfirm(type,index,fromFullTime=false){if(role!=='host'||actionLock)return;actionLock=true;pending={type,index,fromFullTime};if(!fromFullTime)pauseClock();if(type==='goal'){let s=state.playing[index];E.confirmTitle.textContent=`${s.name} scored?`;E.confirmText.textContent='The match ends immediately. Winner stays; loser goes to the back.'}else{E.confirmTitle.textContent='Confirm 0–0 draw?';E.confirmText.textContent='Both teams leave and the next two teams enter.'}E.modal.classList.remove('hidden')}
E.aGoal.onclick=()=>openConfirm('goal',0);E.bGoal.onclick=()=>openConfirm('goal',1);E.draw.onclick=()=>openConfirm('draw');
E.cancel.onclick=()=>{let wasFull=pending?.fromFullTime;E.modal.classList.add('hidden');pending=null;actionLock=false;if(!wasFull)startClock();else{fullTimeLock=false;state.remaining=0;render()}};
E.confirm.onclick=()=>{if(!pending)return;let p=pending;pending=null;E.modal.classList.add('hidden');if(p.type==='goal')goal(p.index);else draw();setTimeout(()=>actionLock=false,800)};
function showTransition(kicker,title,text){E.transitionKicker.textContent=kicker;E.transitionTitle.textContent=title;E.transitionText.textContent=text;E.transition.classList.remove('hidden');clearTimeout(window.__tr);window.__tr=setTimeout(()=>E.transition.classList.add('hidden'),1800)}
function goal(i){snap();let w=state.playing[i],l=state.playing[1-i],n=state.queue.shift(),elapsed=state.duration-currentRemaining();w.games=(w.games||0)+1;w.wins=(w.wins||0)+1;w.streak=(w.streak||0)+1;l.games=(l.games||0)+1;l.streak=0;state.history.unshift({type:'win',winner:w.name,loser:l.name,time:`${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`});state.queue.push(l);state.playing=i===0?[w,n]:[n,w];showTransition('GOAL · MATCH OVER',`${w.name} stays on`,`${n.name} is coming on next.`);newMatch()}
function draw(){if(state.queue.length<2){actionLock=false;return toast('Need two waiting teams')}snap();let[a,b]=state.playing;a.games=(a.games||0)+1;b.games=(b.games||0)+1;a.draws=(a.draws||0)+1;b.draws=(b.draws||0)+1;a.streak=0;b.streak=0;let x=state.queue.shift(),y=state.queue.shift();state.history.unshift({type:'draw',a:a.name,b:b.name,time:`${Math.floor(state.duration/60)}:00`});state.queue.push(a,b);state.playing=[x,y];showTransition('0–0 · FULL TIME','Both teams rotate out',`${x.name} vs ${y.name} is next.`);newMatch()}
function newMatch(){freshMatch();render();push()}
E.undo.onclick=()=>{if(actionLock)return;let s=state.snapshots.pop();if(!s)return toast('Nothing to undo');Object.assign(state,JSON.parse(s));freshMatch();render();push();toast('Last result undone')};
E.history.onclick=()=>{E.historyList.innerHTML=state.history.length?state.history.map(h=>h.type==='win'?`<div class="history-item"><strong>${h.winner} beat ${h.loser}</strong><span>Goal at ${h.time}</span></div>`:`<div class="history-item"><strong>${h.a} vs ${h.b} — Draw</strong><span>0–0 after ${h.time}</span></div>`).join('')+'<div class="stats-table">'+[...state.teams].sort((a,b)=>(b.wins||0)-(a.wins||0)).map(t=>`<div><strong>${t.name}</strong><span>${t.games||0} games · ${t.wins||0} wins · ${t.draws||0} draws</span></div>`).join('')+'</div>':'<div class="empty-state">No completed matches yet.</div>';E.sheet.classList.remove('hidden')};E.closeHistory.onclick=()=>E.sheet.classList.add('hidden');
function joinLink(){return `${location.origin}${location.pathname}?room=${roomCode}`}
function openShare(){if(!roomCode)return;E.shareCode.textContent=roomCode;E.qr.innerHTML='';if(window.QRCode)new QRCode(E.qr,{text:joinLink(),width:190,height:190,colorDark:'#07120d',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});E.share.classList.remove('hidden')}
E.room.onclick=openShare;E.closeShare.onclick=()=>E.share.classList.add('hidden');E.copyLink.onclick=async()=>{let link=joinLink();try{if(navigator.share){await navigator.share({title:'PlayNext',text:`Join room ${roomCode}`,url:link})}else{await navigator.clipboard.writeText(link);toast('Join link copied')}}catch(e){}}
E.reset.onclick=()=>{if(confirm(role==='host'?'Leave this hosted session? You can no longer recover it on this phone.':'Leave this room?')){localStorage.removeItem('playnext-host');location.href=location.pathname}};
(async()=>{let q=new URLSearchParams(location.search).get('room');if(q&&/^\d{4}$/.test(q)){E.joinCode.value=q;await joinRoom();return}await recoverHost()})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});